/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RealPhotographyNoAiRouteImport } from './routes/real-photography-no-ai'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LightboxRouteImport } from './routes/lightbox'
import { Route as LicensingRouteImport } from './routes/licensing'
import { Route as LicenceRouteImport } from './routes/licence'
import { Route as ImageSitemapDotxmlRouteImport } from './routes/image-sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ImageIdRouteImport } from './routes/image.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminFeaturedRouteImport } from './routes/admin.featured'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicDownloadRouteImport } from './routes/api/public/download'
import { Route as ApiAdminUploadImageRouteImport } from './routes/api/admin/upload-image'
import { Route as AdminImageIdRouteImport } from './routes/admin.image.$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPreviewImageIdRouteImport } from './routes/api/public/preview-image.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksProcessPendingRouteImport } from './routes/api/public/hooks/process-pending'
import { Route as ApiPublicHooksKeywordPendingRouteImport } from './routes/api/public/hooks/keyword-pending'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RealPhotographyNoAiRoute = RealPhotographyNoAiRouteImport.update({
  id: '/real-photography-no-ai',
  path: '/real-photography-no-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LightboxRoute = LightboxRouteImport.update({
  id: '/lightbox',
  path: '/lightbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensingRoute = LicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenceRoute = LicenceRouteImport.update({
  id: '/licence',
  path: '/licence',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageSitemapDotxmlRoute = ImageSitemapDotxmlRouteImport.update({
  id: '/image-sitemap.xml',
  path: '/image-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ImageIdRoute = ImageIdRouteImport.update({
  id: '/image/$id',
  path: '/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturedRoute = AdminFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadRoute = ApiPublicDownloadRouteImport.update({
  id: '/api/public/download',
  path: '/api/public/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadImageRoute = ApiAdminUploadImageRouteImport.update({
  id: '/api/admin/upload-image',
  path: '/api/admin/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImageIdRoute = AdminImageIdRouteImport.update({
  id: '/image/$id',
  path: '/image/$id',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPreviewImageIdRoute = ApiPublicPreviewImageIdRouteImport.update({
  id: '/api/public/preview-image/$id',
  path: '/api/public/preview-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessPendingRoute =
  ApiPublicHooksProcessPendingRouteImport.update({
    id: '/api/public/hooks/process-pending',
    path: '/api/public/hooks/process-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKeywordPendingRoute =
  ApiPublicHooksKeywordPendingRouteImport.update({
    id: '/api/public/hooks/keyword-pending',
    path: '/api/public/hooks/keyword-pending',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/basket': typeof BasketRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/image-sitemap.xml': typeof ImageSitemapDotxmlRoute
  '/licence': typeof LicenceRoute
  '/licensing': typeof LicensingRoute
  '/lightbox': typeof LightboxRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/real-photography-no-ai': typeof RealPhotographyNoAiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/image/$id': typeof ImageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/keyword-pending': typeof ApiPublicHooksKeywordPendingRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/preview-image/$id': typeof ApiPublicPreviewImageIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/basket': typeof BasketRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/image-sitemap.xml': typeof ImageSitemapDotxmlRoute
  '/licence': typeof LicenceRoute
  '/licensing': typeof LicensingRoute
  '/lightbox': typeof LightboxRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/real-photography-no-ai': typeof RealPhotographyNoAiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/image/$id': typeof ImageIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/keyword-pending': typeof ApiPublicHooksKeywordPendingRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/preview-image/$id': typeof ApiPublicPreviewImageIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/basket': typeof BasketRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/image-sitemap.xml': typeof ImageSitemapDotxmlRoute
  '/licence': typeof LicenceRoute
  '/licensing': typeof LicensingRoute
  '/lightbox': typeof LightboxRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/real-photography-no-ai': typeof RealPhotographyNoAiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/image/$id': typeof ImageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/keyword-pending': typeof ApiPublicHooksKeywordPendingRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/preview-image/$id': typeof ApiPublicPreviewImageIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/basket'
    | '/collections'
    | '/contact'
    | '/image-sitemap.xml'
    | '/licence'
    | '/licensing'
    | '/lightbox'
    | '/login'
    | '/privacy'
    | '/real-photography-no-ai'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/checkout/return'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/image/$id'
    | '/admin/'
    | '/admin/image/$id'
    | '/api/admin/upload-image'
    | '/api/public/download'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/api/public/hooks/keyword-pending'
    | '/api/public/hooks/process-pending'
    | '/api/public/payments/webhook'
    | '/api/public/preview-image/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/basket'
    | '/collections'
    | '/contact'
    | '/image-sitemap.xml'
    | '/licence'
    | '/licensing'
    | '/lightbox'
    | '/login'
    | '/privacy'
    | '/real-photography-no-ai'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/checkout/return'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/image/$id'
    | '/admin'
    | '/admin/image/$id'
    | '/api/admin/upload-image'
    | '/api/public/download'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/api/public/hooks/keyword-pending'
    | '/api/public/hooks/process-pending'
    | '/api/public/payments/webhook'
    | '/api/public/preview-image/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/basket'
    | '/collections'
    | '/contact'
    | '/image-sitemap.xml'
    | '/licence'
    | '/licensing'
    | '/lightbox'
    | '/login'
    | '/privacy'
    | '/real-photography-no-ai'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/checkout/return'
    | '/collections/$slug'
    | '/email/unsubscribe'
    | '/image/$id'
    | '/admin/'
    | '/admin/image/$id'
    | '/api/admin/upload-image'
    | '/api/public/download'
    | '/api/public/track'
    | '/lovable/email/suppression'
    | '/api/public/hooks/keyword-pending'
    | '/api/public/hooks/process-pending'
    | '/api/public/payments/webhook'
    | '/api/public/preview-image/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BasketRoute: typeof BasketRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  ImageSitemapDotxmlRoute: typeof ImageSitemapDotxmlRoute
  LicenceRoute: typeof LicenceRoute
  LicensingRoute: typeof LicensingRoute
  LightboxRoute: typeof LightboxRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RealPhotographyNoAiRoute: typeof RealPhotographyNoAiRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ImageIdRoute: typeof ImageIdRoute
  ApiAdminUploadImageRoute: typeof ApiAdminUploadImageRoute
  ApiPublicDownloadRoute: typeof ApiPublicDownloadRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksKeywordPendingRoute: typeof ApiPublicHooksKeywordPendingRoute
  ApiPublicHooksProcessPendingRoute: typeof ApiPublicHooksProcessPendingRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPreviewImageIdRoute: typeof ApiPublicPreviewImageIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-photography-no-ai': {
      id: '/real-photography-no-ai'
      path: '/real-photography-no-ai'
      fullPath: '/real-photography-no-ai'
      preLoaderRoute: typeof RealPhotographyNoAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lightbox': {
      id: '/lightbox'
      path: '/lightbox'
      fullPath: '/lightbox'
      preLoaderRoute: typeof LightboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licensing': {
      id: '/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof LicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licence': {
      id: '/licence'
      path: '/licence'
      fullPath: '/licence'
      preLoaderRoute: typeof LicenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-sitemap.xml': {
      id: '/image-sitemap.xml'
      path: '/image-sitemap.xml'
      fullPath: '/image-sitemap.xml'
      preLoaderRoute: typeof ImageSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/image/$id': {
      id: '/image/$id'
      path: '/image/$id'
      fullPath: '/image/$id'
      preLoaderRoute: typeof ImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/featured': {
      id: '/admin/featured'
      path: '/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AdminFeaturedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download': {
      id: '/api/public/download'
      path: '/api/public/download'
      fullPath: '/api/public/download'
      preLoaderRoute: typeof ApiPublicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-image': {
      id: '/api/admin/upload-image'
      path: '/api/admin/upload-image'
      fullPath: '/api/admin/upload-image'
      preLoaderRoute: typeof ApiAdminUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/image/$id': {
      id: '/admin/image/$id'
      path: '/image/$id'
      fullPath: '/admin/image/$id'
      preLoaderRoute: typeof AdminImageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/preview-image/$id': {
      id: '/api/public/preview-image/$id'
      path: '/api/public/preview-image/$id'
      fullPath: '/api/public/preview-image/$id'
      preLoaderRoute: typeof ApiPublicPreviewImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-pending': {
      id: '/api/public/hooks/process-pending'
      path: '/api/public/hooks/process-pending'
      fullPath: '/api/public/hooks/process-pending'
      preLoaderRoute: typeof ApiPublicHooksProcessPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/keyword-pending': {
      id: '/api/public/hooks/keyword-pending'
      path: '/api/public/hooks/keyword-pending'
      fullPath: '/api/public/hooks/keyword-pending'
      preLoaderRoute: typeof ApiPublicHooksKeywordPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFeaturedRoute: typeof AdminFeaturedRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminImageIdRoute: typeof AdminImageIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFeaturedRoute: AdminFeaturedRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminImageIdRoute: AdminImageIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BasketRoute: BasketRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  ImageSitemapDotxmlRoute: ImageSitemapDotxmlRoute,
  LicenceRoute: LicenceRoute,
  LicensingRoute: LicensingRoute,
  LightboxRoute: LightboxRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RealPhotographyNoAiRoute: RealPhotographyNoAiRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ImageIdRoute: ImageIdRoute,
  ApiAdminUploadImageRoute: ApiAdminUploadImageRoute,
  ApiPublicDownloadRoute: ApiPublicDownloadRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksKeywordPendingRoute: ApiPublicHooksKeywordPendingRoute,
  ApiPublicHooksProcessPendingRoute: ApiPublicHooksProcessPendingRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPreviewImageIdRoute: ApiPublicPreviewImageIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
