/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LightboxRouteImport } from './routes/lightbox'
import { Route as DesignRouteImport } from './routes/design'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ImageIdRouteImport } from './routes/image.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminFeaturedRouteImport } from './routes/admin.featured'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicDownloadRouteImport } from './routes/api/public/download'
import { Route as AdminImageIdRouteImport } from './routes/admin.image.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksProcessPendingRouteImport } from './routes/api/public/hooks/process-pending'
import { Route as ApiPublicHooksKeywordPendingRouteImport } from './routes/api/public/hooks/keyword-pending'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LightboxRoute = LightboxRouteImport.update({
  id: '/lightbox',
  path: '/lightbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ImageIdRoute = ImageIdRouteImport.update({
  id: '/image/$id',
  path: '/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturedRoute = AdminFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadRoute = ApiPublicDownloadRouteImport.update({
  id: '/api/public/download',
  path: '/api/public/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImageIdRoute = AdminImageIdRouteImport.update({
  id: '/image/$id',
  path: '/image/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessPendingRoute =
  ApiPublicHooksProcessPendingRouteImport.update({
    id: '/api/public/hooks/process-pending',
    path: '/api/public/hooks/process-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKeywordPendingRoute =
  ApiPublicHooksKeywordPendingRouteImport.update({
    id: '/api/public/hooks/keyword-pending',
    path: '/api/public/hooks/keyword-pending',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/basket': typeof BasketRoute
  '/design': typeof DesignRoute
  '/lightbox': typeof LightboxRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/image/$id': typeof ImageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/hooks/keyword-pending': typeof ApiPublicHooksKeywordPendingRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/basket': typeof BasketRoute
  '/design': typeof DesignRoute
  '/lightbox': typeof LightboxRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/image/$id': typeof ImageIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/hooks/keyword-pending': typeof ApiPublicHooksKeywordPendingRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/basket': typeof BasketRoute
  '/design': typeof DesignRoute
  '/lightbox': typeof LightboxRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/image/$id': typeof ImageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/hooks/keyword-pending': typeof ApiPublicHooksKeywordPendingRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/basket'
    | '/design'
    | '/lightbox'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/checkout/return'
    | '/image/$id'
    | '/admin/'
    | '/admin/image/$id'
    | '/api/public/download'
    | '/api/public/track'
    | '/api/public/hooks/keyword-pending'
    | '/api/public/hooks/process-pending'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/basket'
    | '/design'
    | '/lightbox'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/checkout/return'
    | '/image/$id'
    | '/admin'
    | '/admin/image/$id'
    | '/api/public/download'
    | '/api/public/track'
    | '/api/public/hooks/keyword-pending'
    | '/api/public/hooks/process-pending'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/basket'
    | '/design'
    | '/lightbox'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/checkout/return'
    | '/image/$id'
    | '/admin/'
    | '/admin/image/$id'
    | '/api/public/download'
    | '/api/public/track'
    | '/api/public/hooks/keyword-pending'
    | '/api/public/hooks/process-pending'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BasketRoute: typeof BasketRoute
  DesignRoute: typeof DesignRoute
  LightboxRoute: typeof LightboxRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ImageIdRoute: typeof ImageIdRoute
  ApiPublicDownloadRoute: typeof ApiPublicDownloadRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicHooksKeywordPendingRoute: typeof ApiPublicHooksKeywordPendingRoute
  ApiPublicHooksProcessPendingRoute: typeof ApiPublicHooksProcessPendingRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lightbox': {
      id: '/lightbox'
      path: '/lightbox'
      fullPath: '/lightbox'
      preLoaderRoute: typeof LightboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/image/$id': {
      id: '/image/$id'
      path: '/image/$id'
      fullPath: '/image/$id'
      preLoaderRoute: typeof ImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/featured': {
      id: '/admin/featured'
      path: '/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AdminFeaturedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download': {
      id: '/api/public/download'
      path: '/api/public/download'
      fullPath: '/api/public/download'
      preLoaderRoute: typeof ApiPublicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/image/$id': {
      id: '/admin/image/$id'
      path: '/image/$id'
      fullPath: '/admin/image/$id'
      preLoaderRoute: typeof AdminImageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-pending': {
      id: '/api/public/hooks/process-pending'
      path: '/api/public/hooks/process-pending'
      fullPath: '/api/public/hooks/process-pending'
      preLoaderRoute: typeof ApiPublicHooksProcessPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/keyword-pending': {
      id: '/api/public/hooks/keyword-pending'
      path: '/api/public/hooks/keyword-pending'
      fullPath: '/api/public/hooks/keyword-pending'
      preLoaderRoute: typeof ApiPublicHooksKeywordPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFeaturedRoute: typeof AdminFeaturedRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminImageIdRoute: typeof AdminImageIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFeaturedRoute: AdminFeaturedRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminImageIdRoute: AdminImageIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BasketRoute: BasketRoute,
  DesignRoute: DesignRoute,
  LightboxRoute: LightboxRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ImageIdRoute: ImageIdRoute,
  ApiPublicDownloadRoute: ApiPublicDownloadRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicHooksKeywordPendingRoute: ApiPublicHooksKeywordPendingRoute,
  ApiPublicHooksProcessPendingRoute: ApiPublicHooksProcessPendingRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
