/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LightboxRouteImport } from './routes/lightbox'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ImageIdRouteImport } from './routes/image.$id'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminFeaturedRouteImport } from './routes/admin.featured'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AdminImageIdRouteImport } from './routes/admin.image.$id'

const LightboxRoute = LightboxRouteImport.update({
  id: '/lightbox',
  path: '/lightbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const LightboxRoute = LightboxRouteImport.update({
  id: '/lightbox',
  path: '/lightbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ImageIdRoute = ImageIdRouteImport.update({
  id: '/image/$id',
  path: '/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturedRoute = AdminFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImageIdRoute = AdminImageIdRouteImport.update({
  id: '/image/$id',
  path: '/image/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design': typeof DesignRoute
  '/lightbox': typeof LightboxRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/image/$id': typeof ImageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/lightbox': typeof LightboxRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/image/$id': typeof ImageIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design': typeof DesignRoute
  '/lightbox': typeof LightboxRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/featured': typeof AdminFeaturedRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/image/$id': typeof ImageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/image/$id': typeof AdminImageIdRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design'
    | '/lightbox'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/image/$id'
    | '/admin/'
    | '/admin/image/$id'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/lightbox'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/image/$id'
    | '/admin'
    | '/admin/image/$id'
    | '/api/public/track'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design'
    | '/lightbox'
    | '/admin/customers'
    | '/admin/featured'
    | '/admin/library'
    | '/admin/login'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/upload'
    | '/image/$id'
    | '/admin/'
    | '/admin/image/$id'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DesignRoute: typeof DesignRoute
  LightboxRoute: typeof LightboxRoute
  ImageIdRoute: typeof ImageIdRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lightbox': {
      id: '/lightbox'
      path: '/lightbox'
      fullPath: '/lightbox'
      preLoaderRoute: typeof LightboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/image/$id': {
      id: '/image/$id'
      path: '/image/$id'
      fullPath: '/image/$id'
      preLoaderRoute: typeof ImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/featured': {
      id: '/admin/featured'
      path: '/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AdminFeaturedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/image/$id': {
      id: '/admin/image/$id'
      path: '/image/$id'
      fullPath: '/admin/image/$id'
      preLoaderRoute: typeof AdminImageIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFeaturedRoute: typeof AdminFeaturedRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminImageIdRoute: typeof AdminImageIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFeaturedRoute: AdminFeaturedRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminImageIdRoute: AdminImageIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DesignRoute: DesignRoute,
  LightboxRoute: LightboxRoute,
  ImageIdRoute: ImageIdRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
